# Generated by Django 5.2 on 2025-04-24 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0003_profissionalsaude_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='profissionais.profissionalsaude')),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
                'unique_together': {('profissional', 'data', 'hora_inicio')},
            },
        ),
    ]
