# Generated by Django 5.2 on 2025-04-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_initial'),
        ('profissionais', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_alta', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('leito', models.CharField(blank=True, max_length=20, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='pacientes.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internacoes', to='profissionais.profissionalsaude')),
            ],
        ),
    ]
