# Generated by Django 5.2 on 2025-04-23 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_initial'),
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='unidade.unidadehospitalar'),
        ),
    ]
